added support for generating prediction output files compatible to official evaluation scripts
ElementAI/picard pull request #76
Opened 2022-03-15 14:36 UTC by kotalaraghava

Hey @tscholak ,

#17

I have added code corresponding to generating output SQL files. 

[seq2seq/prediction_output.py](
https://github.com/kotalaraghava/picard/blob/95f3c2af0907409416f933bfd927b59ed89b9732/seq2seq/prediction_output.py) this is a copy of the codalab_seq2seq.py file. Changed the names and fixed the above-mentioned bug.

[configs/prediction_output.json](https://github.com/kotalaraghava/picard/blob/95f3c2af0907409416f933bfd927b59ed89b9732/configs/prediction_output.json) this is a config file according to arguments required to run.

Config file discription:
`inputs_path ` : Path to dev.json file 
`output_path` : prediction_sql.txt file location.
`db_path` : sqalite file path corresponding to dev.json file.
`conversational` : true incase of cosql_data or false for spider.

And changed to Makefile to make it invoke through `prediction_output` string.
https://github.com/kotalaraghava/picard/blob/95f3c2af0907409416f933bfd927b59ed89b9732/Makefile

I have tested it with previous docker images by mounting this code. and it's working fine.

I hope this helps.

Thanks,
Raghav

2022-03-15 21:49 UTC, tscholak requested changes
Thanks, this is excellent work!
I only have minor suggestions and comments.

In addition to the inline comments, please use `git mv` to rename the codalab script to `prediction_output.py`. This will remove the old non-functional codalab script and replace it with your code. I find that less confusing, and it makes it easier to track what has changed. When you do that, be careful not to overwrite your code by accident. I suggest you make a copy of your current `prediction_output.py` before and overwrite the codalab script with your copy once you've run `git mv codalab_seq2seq.py prediction_output.py `.

2022-03-15 21:49 UTC, tscholak commented on Makefile
> +		--mount type=bind,source=$(BASE_DIR)/seq2seq,target=/app/seq2seq \
Can you remove this line please? This is fine during development, but once this PR is merged, the code should come from the official images.

2022-03-15 21:49 UTC, tscholak commented on seq2seq/prediction_output.py
> +class PredictionOutput:
```suggestion
class PredictionOutputArguments:
```
Otherwise, it sounds like this is a data class for the outputs themselves.

2022-03-15 21:49 UTC, tscholak commented on seq2seq/prediction_output.py
> +    Arguments pertaining to codalab execution.
```suggestion
    Arguments pertaining to execution.
```

2022-03-15 21:49 UTC, tscholak commented on seq2seq/prediction_output.py
> +    codalab_args: PredictionOutput
```suggestion
    prediction_output_args: PredictionOutputArguments
```

2022-03-16 14:00 UTC, kotalaraghava commented
Hey @tscholak ,

I agree with all changes you suggested and I have made other commits containing all changes. kindly check once.

Let me know if you feel like any other changes are required.

Thanks,
Raghav

2022-03-16 15:31 UTC, tscholak requested changes
Hi, looks much better, thanks!
I saw that you removed some arguments from the pipes, most importantly `num_beams`. I think you should revert that change. Once this is done, it's good to go!

2022-03-16 15:41 UTC, tscholak approved these changes
Never mind, I made a wrong assessment because I overlooked code that sets the beam size. LGTM!

2022-03-16 15:42 UTC, merged

2022-03-16 15:42 UTC, tscholak commented
Thanks again for this contribution!